# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dssGUI.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWebEngineWidgets
from PyQt5.QtCore import QUrl, QEventLoop

class Ui_PyDSS(object):
    def setupUi(self, PyDSS):
        PyDSS.setObjectName("PyDSS")
        PyDSS.setWindowModality(QtCore.Qt.ApplicationModal)
        PyDSS.resize(1102, 624)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        PyDSS.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/PyDSS.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PyDSS.setWindowIcon(icon)
        PyDSS.setWindowOpacity(4.0)
        self.tabWidget = QtWidgets.QTabWidget(PyDSS)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1081, 601))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(8, 10, 191, 21))
        self.label_7.setObjectName("label_7")
        self.treeView_ProjectBrowser = QtWidgets.QTreeView(self.tab)
        self.treeView_ProjectBrowser.setGeometry(QtCore.QRect(10, 40, 256, 231))
        self.treeView_ProjectBrowser.setObjectName("treeView_ProjectBrowser")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(280, 30, 381, 241))
        self.groupBox.setObjectName("groupBox")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 191, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 65, 191, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(20, 100, 191, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(20, 200, 191, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(20, 134, 191, 21))
        self.label_12.setObjectName("label_12")
        self.spinBox_StartDay = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_StartDay.setGeometry(QtCore.QRect(100, 30, 261, 23))
        self.spinBox_StartDay.setMaximum(10000)
        self.spinBox_StartDay.setObjectName("spinBox_StartDay")
        self.spinBox_EndDay = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_EndDay.setGeometry(QtCore.QRect(100, 65, 261, 23))
        self.spinBox_EndDay.setMaximum(10000)
        self.spinBox_EndDay.setProperty("value", 1)
        self.spinBox_EndDay.setObjectName("spinBox_EndDay")
        self.spinBox_TimeStep = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_TimeStep.setGeometry(QtCore.QRect(140, 100, 221, 23))
        self.spinBox_TimeStep.setProperty("value", 15)
        self.spinBox_TimeStep.setObjectName("spinBox_TimeStep")
        self.comboBox_SimType = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_SimType.setGeometry(QtCore.QRect(140, 134, 221, 23))
        self.comboBox_SimType.setEditable(False)
        self.comboBox_SimType.setMinimumContentsLength(2)
        self.comboBox_SimType.setObjectName("comboBox_SimType")
        self.comboBox_SimType.addItem("")
        self.comboBox_SimType.addItem("")
        self.comboBox_SimType.addItem("")
        self.comboBox_SimType.addItem("")
        self.spinBox_MaxItr = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_MaxItr.setGeometry(QtCore.QRect(200, 200, 161, 23))
        self.spinBox_MaxItr.setProperty("value", 10)
        self.spinBox_MaxItr.setObjectName("spinBox_MaxItr")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(20, 170, 191, 21))
        self.label_15.setObjectName("label_15")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setGeometry(QtCore.QRect(171, 169, 191, 23))
        self.doubleSpinBox.setMaximum(10000.0)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(680, 29, 381, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(20, 40, 191, 21))
        self.label_14.setObjectName("label_14")
        self.label_ = QtWidgets.QLabel(self.groupBox_2)
        self.label_.setGeometry(QtCore.QRect(20, 160, 191, 21))
        self.label_.setObjectName("label_")
        self.label_LogExtFile = QtWidgets.QLabel(self.groupBox_2)
        self.label_LogExtFile.setGeometry(QtCore.QRect(20, 80, 191, 21))
        self.label_LogExtFile.setObjectName("label_LogExtFile")
        self.label_LogScreen = QtWidgets.QLabel(self.groupBox_2)
        self.label_LogScreen.setGeometry(QtCore.QRect(20, 120, 191, 21))
        self.label_LogScreen.setObjectName("label_LogScreen")
        self.comboBox_LogLvl = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_LogLvl.setGeometry(QtCore.QRect(150, 40, 211, 23))
        self.comboBox_LogLvl.setObjectName("comboBox_LogLvl")
        self.comboBox_LogLvl.addItem("")
        self.comboBox_LogLvl.addItem("")
        self.comboBox_LogLvl.addItem("")
        self.comboBox_LogExtFile = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_LogExtFile.setGeometry(QtCore.QRect(150, 78, 211, 23))
        self.comboBox_LogExtFile.setObjectName("comboBox_LogExtFile")
        self.comboBox_LogExtFile.addItem("")
        self.comboBox_LogExtFile.addItem("")
        self.comboBox_DelLog = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_DelLog.setGeometry(QtCore.QRect(150, 158, 211, 23))
        self.comboBox_DelLog.setObjectName("comboBox_DelLog")
        self.comboBox_DelLog.addItem("")
        self.comboBox_DelLog.addItem("")
        self.comboBox_LogScreen = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_LogScreen.setGeometry(QtCore.QRect(150, 120, 211, 23))
        self.comboBox_LogScreen.setObjectName("comboBox_LogScreen")
        self.comboBox_LogScreen.addItem("")
        self.comboBox_LogScreen.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 281, 381, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_NetworkLayout = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_NetworkLayout.setGeometry(QtCore.QRect(20, 30, 181, 21))
        self.checkBox_NetworkLayout.setObjectName("checkBox_NetworkLayout")
        self.checkBox_XY = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_XY.setGeometry(QtCore.QRect(20, 90, 181, 21))
        self.checkBox_XY.setObjectName("checkBox_XY")
        self.checkBox_TimeSeries = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_TimeSeries.setGeometry(QtCore.QRect(20, 60, 181, 21))
        self.checkBox_TimeSeries.setObjectName("checkBox_TimeSeries")
        self.checkBox_Histogram = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_Histogram.setGeometry(QtCore.QRect(210, 60, 181, 21))
        self.checkBox_Histogram.setObjectName("checkBox_Histogram")
        self.checkBox_GIS = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_GIS.setGeometry(QtCore.QRect(210, 90, 181, 21))
        self.checkBox_GIS.setObjectName("checkBox_GIS")
        self.checkBox_VD = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_VD.setGeometry(QtCore.QRect(210, 30, 181, 21))
        self.checkBox_VD.setObjectName("checkBox_VD")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(680, 240, 381, 151))
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(20, 32, 191, 21))
        self.label_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(20, 108, 191, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(20, 71, 191, 21))
        self.label_20.setObjectName("label_20")
        self.comboBox_ExportMode = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_ExportMode.setGeometry(QtCore.QRect(150, 68, 211, 23))
        self.comboBox_ExportMode.setObjectName("comboBox_ExportMode")
        self.comboBox_ExportMode.addItem("")
        self.comboBox_ExportMode.addItem("")
        self.comboBox_ExportResults = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_ExportResults.setGeometry(QtCore.QRect(150, 30, 211, 23))
        self.comboBox_ExportResults.setObjectName("comboBox_ExportResults")
        self.comboBox_ExportResults.addItem("")
        self.comboBox_ExportResults.addItem("")
        self.comboBox_ExportStyle = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_ExportStyle.setGeometry(QtCore.QRect(150, 106, 211, 23))
        self.comboBox_ExportStyle.setObjectName("comboBox_ExportStyle")
        self.comboBox_ExportStyle.addItem("")
        self.comboBox_ExportStyle.addItem("")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(10, 280, 191, 21))
        self.label_13.setObjectName("label_13")
        self.listWidget_opendssfiles = QtWidgets.QListWidget(self.tab)
        self.listWidget_opendssfiles.setGeometry(QtCore.QRect(10, 310, 256, 161))
        self.listWidget_opendssfiles.setObjectName("listWidget_opendssfiles")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setEnabled(False)
        self.groupBox_5.setGeometry(QtCore.QRect(680, 400, 381, 161))
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setEnabled(False)
        self.groupBox_6.setGeometry(QtCore.QRect(280, 410, 381, 151))
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_RunSimulation = QtWidgets.QPushButton(self.tab)
        self.pushButton_RunSimulation.setGeometry(QtCore.QRect(10, 490, 256, 28))
        self.pushButton_RunSimulation.setObjectName("pushButton_RunSimulation")
        self.pushButton_Exit = QtWidgets.QPushButton(self.tab)
        self.pushButton_Exit.setGeometry(QtCore.QRect(10, 530, 255, 28))
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(210, 10, 191, 21))
        self.label_5.setObjectName("label_5")
        self.tableWidget_CtrlTable = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_CtrlTable.setGeometry(QtCore.QRect(210, 40, 851, 521))
        self.tableWidget_CtrlTable.setObjectName("tableWidget_CtrlTable")
        self.tableWidget_CtrlTable.setColumnCount(0)
        self.tableWidget_CtrlTable.setRowCount(0)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(8, 10, 191, 21))
        self.label_6.setObjectName("label_6")
        self.pushButton_CtrlDel = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_CtrlDel.setGeometry(QtCore.QRect(9, 490, 191, 31))
        self.pushButton_CtrlDel.setObjectName("pushButton_CtrlDel")
        self.pushButton_CtrlNew = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_CtrlNew.setGeometry(QtCore.QRect(9, 530, 191, 31))
        self.pushButton_CtrlNew.setObjectName("pushButton_CtrlNew")
        self.listWidget_CtrlFiles = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_CtrlFiles.setGeometry(QtCore.QRect(9, 41, 191, 431))
        self.listWidget_CtrlFiles.setObjectName("listWidget_CtrlFiles")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.listWidget_PltFiles = QtWidgets.QListWidget(self.tab_3)
        self.listWidget_PltFiles.setGeometry(QtCore.QRect(10, 40, 191, 431))
        self.listWidget_PltFiles.setObjectName("listWidget_PltFiles")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(210, 10, 191, 21))
        self.label_3.setObjectName("label_3")
        self.tableWidget_PltTable = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_PltTable.setGeometry(QtCore.QRect(210, 40, 851, 521))
        self.tableWidget_PltTable.setObjectName("tableWidget_PltTable")
        self.tableWidget_PltTable.setColumnCount(0)
        self.tableWidget_PltTable.setRowCount(0)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(8, 10, 191, 21))
        self.label_4.setObjectName("label_4")
        self.pushButton_pltdel = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_pltdel.setGeometry(QtCore.QRect(10, 490, 191, 31))
        self.pushButton_pltdel.setObjectName("pushButton_pltdel")
        self.pushButton_PltNew = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_PltNew.setGeometry(QtCore.QRect(10, 530, 191, 31))
        self.pushButton_PltNew.setObjectName("pushButton_PltNew")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_ExpTable = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_ExpTable.setGeometry(QtCore.QRect(210, 40, 851, 521))
        self.tableWidget_ExpTable.setObjectName("tableWidget_ExpTable")
        self.tableWidget_ExpTable.setColumnCount(0)
        self.tableWidget_ExpTable.setRowCount(0)
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(8, 10, 191, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(210, 10, 191, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton_ExpDel = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_ExpDel.setGeometry(QtCore.QRect(10, 490, 191, 31))
        self.pushButton_ExpDel.setObjectName("pushButton_ExpDel")
        self.pushButton_ExpNew = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_ExpNew.setGeometry(QtCore.QRect(10, 530, 191, 31))
        self.pushButton_ExpNew.setObjectName("pushButton_ExpNew")
        self.listWidget_ExpFiles = QtWidgets.QListWidget(self.tab_4)
        self.listWidget_ExpFiles.setGeometry(QtCore.QRect(10, 40, 191, 431))
        self.listWidget_ExpFiles.setObjectName("listWidget_ExpFiles")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.treeView_PythonFiles = QtWidgets.QTreeView(self.tab_7)
        self.treeView_PythonFiles.setGeometry(QtCore.QRect(10, 40, 201, 431))
        self.treeView_PythonFiles.setObjectName("treeView_PythonFiles")
        self.pushButton_NewPython = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_NewPython.setGeometry(QtCore.QRect(10, 530, 201, 31))
        self.pushButton_NewPython.setObjectName("pushButton_NewPython")
        self.pushButton_PythonEdit = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_PythonEdit.setGeometry(QtCore.QRect(10, 490, 201, 31))
        self.pushButton_PythonEdit.setObjectName("pushButton_PythonEdit")
        self.textEdit_Python = QtWidgets.QTextEdit(self.tab_7)
        self.textEdit_Python.setGeometry(QtCore.QRect(220, 40, 841, 521))
        self.textEdit_Python.setObjectName("textEdit_Python")
        self.label_21 = QtWidgets.QLabel(self.tab_7)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 191, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_7)
        self.label_22.setGeometry(QtCore.QRect(220, 10, 191, 21))
        self.label_22.setObjectName("label_22")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")


        self.WebViewer = QtWebEngineWidgets.QWebEngineView(self.tab_6)
        self.WebViewer.setGeometry(QtCore.QRect(15, 10, 1050, 550))
        self.WebViewer.setObjectName("WebViewer")
        self.WebViewer.load(QUrl("http://dpv.epri.com/opendss.html"))


        self.tabWidget.addTab(self.tab_6, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.treeView_Results = QtWidgets.QTreeView(self.tab_15)
        self.treeView_Results.setGeometry(QtCore.QRect(10, 40, 261, 231))
        self.treeView_Results.setObjectName("treeView_Results")
        self.label_46 = QtWidgets.QLabel(self.tab_15)
        self.label_46.setGeometry(QtCore.QRect(10, 10, 191, 21))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.tab_15)
        self.label_47.setGeometry(QtCore.QRect(290, 10, 191, 21))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.tab_15)
        self.label_48.setGeometry(QtCore.QRect(10, 280, 191, 21))
        self.label_48.setObjectName("label_48")
        self.listWidget_Results = QtWidgets.QListWidget(self.tab_15)
        self.listWidget_Results.setGeometry(QtCore.QRect(10, 310, 261, 251))
        self.listWidget_Results.setObjectName("listWidget_Results")
        self.tabWidget.addTab(self.tab_15, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.textBrowser_Log = QtWidgets.QTextBrowser(self.tab_5)
        self.textBrowser_Log.setGeometry(QtCore.QRect(10, 41, 1051, 481))
        self.textBrowser_Log.setObjectName("textBrowser_Log")
        self.pushButton_ClearLog = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_ClearLog.setGeometry(QtCore.QRect(807, 530, 255, 28))
        self.pushButton_ClearLog.setObjectName("pushButton_ClearLog")
        self.pushButton_SaveLog = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_SaveLog.setGeometry(QtCore.QRect(540, 530, 255, 28))
        self.pushButton_SaveLog.setObjectName("pushButton_SaveLog")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 191, 21))
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.tab_5, "")

        self.retranslateUi(PyDSS)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PyDSS)

    def retranslateUi(self, PyDSS):
        _translate = QtCore.QCoreApplication.translate
        PyDSS.setWindowTitle(_translate("PyDSS", "PyDSS"))
        self.label_7.setText(_translate("PyDSS", "Project browser"))
        self.groupBox.setTitle(_translate("PyDSS", "Simulation settings"))
        self.label_8.setText(_translate("PyDSS", "Start day"))
        self.label_9.setText(_translate("PyDSS", "End day"))
        self.label_10.setText(_translate("PyDSS", "Time step (min)"))
        self.label_11.setText(_translate("PyDSS", "Maximum control iterations"))
        self.label_12.setText(_translate("PyDSS", "Simulation type"))
        self.comboBox_SimType.setCurrentText(_translate("PyDSS", "Quasi static time series"))
        self.comboBox_SimType.setItemText(0, _translate("PyDSS", "Quasi static time series"))
        self.comboBox_SimType.setItemText(1, _translate("PyDSS", "Snapshot"))
        self.comboBox_SimType.setItemText(2, _translate("PyDSS", "Monte Carlo"))
        self.comboBox_SimType.setItemText(3, _translate("PyDSS", "Temporal parallelization"))
        self.label_15.setText(_translate("PyDSS", "Error tolerance (kVA)"))
        self.groupBox_2.setTitle(_translate("PyDSS", "Logger settings"))
        self.label_14.setText(_translate("PyDSS", "Logging level"))
        self.label_.setText(_translate("PyDSS", "Clear old log files"))
        self.label_LogExtFile.setText(_translate("PyDSS", "Log to external file"))
        self.label_LogScreen.setText(_translate("PyDSS", "Display on screen"))
        self.comboBox_LogLvl.setItemText(0, _translate("PyDSS", "DEBUG"))
        self.comboBox_LogLvl.setItemText(1, _translate("PyDSS", "WARNING"))
        self.comboBox_LogLvl.setItemText(2, _translate("PyDSS", "INFO"))
        self.comboBox_LogExtFile.setItemText(0, _translate("PyDSS", "True"))
        self.comboBox_LogExtFile.setItemText(1, _translate("PyDSS", "False"))
        self.comboBox_DelLog.setItemText(0, _translate("PyDSS", "True"))
        self.comboBox_DelLog.setItemText(1, _translate("PyDSS", "False"))
        self.comboBox_LogScreen.setItemText(0, _translate("PyDSS", "True"))
        self.comboBox_LogScreen.setItemText(1, _translate("PyDSS", "False"))
        self.groupBox_3.setTitle(_translate("PyDSS", "Plot settings"))
        self.checkBox_NetworkLayout.setText(_translate("PyDSS", "Network layout plot"))
        self.checkBox_XY.setText(_translate("PyDSS", "XY plot"))
        self.checkBox_TimeSeries.setText(_translate("PyDSS", "Time series plot"))
        self.checkBox_Histogram.setText(_translate("PyDSS", "Histogram plot"))
        self.checkBox_GIS.setText(_translate("PyDSS", "GIS overlay plot"))
        self.checkBox_VD.setText(_translate("PyDSS", "Voltage / distance plot"))
        self.groupBox_4.setTitle(_translate("PyDSS", "Export settings"))
        self.label_18.setText(_translate("PyDSS", "Export results"))
        self.label_19.setText(_translate("PyDSS", "Export style"))
        self.label_20.setText(_translate("PyDSS", "Export mode"))
        self.comboBox_ExportMode.setItemText(0, _translate("PyDSS", "byClass"))
        self.comboBox_ExportMode.setItemText(1, _translate("PyDSS", "byElement"))
        self.comboBox_ExportResults.setItemText(0, _translate("PyDSS", "True"))
        self.comboBox_ExportResults.setItemText(1, _translate("PyDSS", "False"))
        self.comboBox_ExportStyle.setItemText(0, _translate("PyDSS", "Single file"))
        self.comboBox_ExportStyle.setItemText(1, _translate("PyDSS", "Seperate files"))
        self.label_13.setText(_translate("PyDSS", "OpenDSS files"))
        self.groupBox_5.setTitle(_translate("PyDSS", "Temporal parallelization settings"))
        self.groupBox_6.setTitle(_translate("PyDSS", "Monte Carlo settings"))
        self.pushButton_RunSimulation.setText(_translate("PyDSS", "Run simulation"))
        self.pushButton_Exit.setText(_translate("PyDSS", "E&xit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PyDSS", "Simulation settings"))
        self.label_5.setText(_translate("PyDSS", "File dataset"))
        self.label_6.setText(_translate("PyDSS", "List of controller files"))
        self.pushButton_CtrlDel.setText(_translate("PyDSS", "Save settings file"))
        self.pushButton_CtrlNew.setText(_translate("PyDSS", "Create new settings file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PyDSS", "Controller settings"))
        self.label_3.setText(_translate("PyDSS", "File dataset"))
        self.label_4.setText(_translate("PyDSS", "List of plot files"))
        self.pushButton_pltdel.setText(_translate("PyDSS", "Save settings file"))
        self.pushButton_PltNew.setText(_translate("PyDSS", "Create new settings file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PyDSS", "Plots settings"))
        self.label.setText(_translate("PyDSS", "List of export files"))
        self.label_2.setText(_translate("PyDSS", "File dataset"))
        self.pushButton_ExpDel.setText(_translate("PyDSS", "Save settings file"))
        self.pushButton_ExpNew.setText(_translate("PyDSS", "Create new settings file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("PyDSS", "Export settings"))
        self.pushButton_NewPython.setText(_translate("PyDSS", "Create new Python file"))
        self.pushButton_PythonEdit.setText(_translate("PyDSS", "Save Python file"))
        self.label_21.setText(_translate("PyDSS", "List of Python files"))
        self.label_22.setText(_translate("PyDSS", "File editor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("PyDSS", "Code editor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("PyDSS", "Plots"))
        self.label_46.setText(_translate("PyDSS", "List of result files"))
        self.label_47.setText(_translate("PyDSS", "Plot "))
        self.label_48.setText(_translate("PyDSS", "Results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("PyDSS", "Results"))
        self.pushButton_ClearLog.setText(_translate("PyDSS", "Clear log file"))
        self.pushButton_SaveLog.setText(_translate("PyDSS", "Save log file"))
        self.label_16.setText(_translate("PyDSS", "List of export files"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("PyDSS", "Log"))

