[PFR_Testing]
"UcalcMode" = "Max"
"Follow standard" = "1547-2018"
"Ride-through Category" = "Category I"
"Category I Low Frequency Droop" = true
"OF2 - Hz" = 62.0
"OF2 CT - sec" = 0.16
"OF1 - Hz" = 61.2
"OF1 CT - sec" = 300
"UF1 - Hz" = 58.5
"UF1 CT - sec" = 300
"UF2 - Hz" = 56.5
"UF2 CT - sec" = 0.16
"db_UF" = 0.036
"db_OF" = 0.036
"k_UF" = 0.01
"k_OF" = 0.01
"T_rf" = 0.001
"T_pord" = 2
"Large_signal_limited" = false
"Reserve Margin" = 0.0
"Reconnect deadtime - sec" = 3000 
"Reconnect Pmax time - sec" = 300
"May trip operation" = "Ride-Through"
"Multiple disturbances" = "Trip"
"Testing block enabled" = true

[FRT_Testing]
"UcalcMode" = "Max"
"Follow standard" = "1547-2018"
"Ride-through Category" = "Category I"
"Category I Low Frequency Droop" = true
"OF2 - Hz" = 62.0
"OF2 CT - sec" = 0.16
"OF1 - Hz" = 61.2
"OF1 CT - sec" = 300
"UF1 - Hz" = 58.5
"UF1 CT - sec" = 300
"UF2 - Hz" = 56.5
"UF2 CT - sec" = 0.16
"db_UF" = 0.036
"db_OF" = 0.036
"k_UF" = 0.01
"k_OF" = 0.01
"T_rf" = 0.001
"T_pord" = 2
"Large_signal_limited" = false
"Reserve Margin" = 0.0
"Reconnect deadtime - sec" = 3000 
"Reconnect Pmax time - sec" = 300
"May trip operation" = "Trip"
"Multiple disturbances" = "Trip"
"Testing block enabled" = true
