[NO_VRT]
"Category" = "test"
"kVA" = 4.0
"maxKW" = 4.0
"KvarLimit"	= 1.76
"%PCutin" = 10.0
"%PCutout" = 10.0
"UcalcMode" = "Max"
"Priority" = "Equal"
"Enable PF limit" = false
"pfMin"	= 0.95
"Follow standard" = "1547-2003"
"Ride-through Category"	= "Category I"
"OV2 - p.u." = 1.2
"OV2 CT - sec" = 0.16
"OV1 - p.u." = 1.2
"OV1 CT - sec" = 2.0
"UV1 - p.u." = 0.8
"UV1 CT - sec" = 2.0
"UV2 - p.u." = 0.5
"UV2 CT - sec" = 0.16
"Reconnect deadtime - sec" = 3000.0
"Reconnect Pmax time - sec" = 300.0
"Permissive operation" = "Current limited"
"May trip operation" = "Trip"
"Multiple disturbances" = "Trip"

[1547_CAT_I]
"Category" = "test"
"kVA" = 4.0
"maxKW" = 4.0
"KvarLimit"	= 1.76
"%PCutin" = 0.0
"%PCutout" = 0.0
"UcalcMode" = "Max"
"Priority" = "Equal"
"Enable PF limit" = false
"pfMin"	= 0.95
"Follow standard" = "1547-2018"
"Ride-through Category"	= "Category I"
"OV2 - p.u." = 1.2
"OV2 CT - sec" = 0.16
"OV1 - p.u." = 1.1
"OV1 CT - sec" = 2.0
"UV1 - p.u." = 0.7
"UV1 CT - sec" = 2.0
"UV2 - p.u." = 0.45
"UV2 CT - sec" = 0.16
"Reconnect deadtime - sec" = 3000.0
"Reconnect Pmax time - sec" = 300.0
"Permissive operation" = "Current limited"
"May trip operation" = "Trip"
"Multiple disturbances" = "Trip"


[1547_CAT_II]
"Category" = "test"
"kVA" = 4.0
"maxKW" = 4.0
"KvarLimit"	= 1.76
"%PCutin" = 0.0
"%PCutout" = 0.0
"UcalcMode" = "Max"
"Priority" = "Equal"
"Enable PF limit" = false
"pfMin"	= 0.95
"Follow standard" = "1547-2018"
"Ride-through Category"	= "Category II"
"OV2 - p.u." = 1.2
"OV2 CT - sec" = 0.16
"OV1 - p.u." = 1.1
"OV1 CT - sec" = 2.0
"UV1 - p.u." = 0.7
"UV1 CT - sec" = 10.0
"UV2 - p.u." = 0.45
"UV2 CT - sec" = 0.16
"Reconnect deadtime - sec" = 3000.0
"Reconnect Pmax time - sec" = 300.0
"Permissive operation" = "Current limited"
"May trip operation" = "Trip"
"Multiple disturbances" = "Trip"


[1547_CAT_III]
"Category" = "test"
"kVA" = 4.0
"maxKW" = 4.0
"KvarLimit"	= 1.76
"%PCutin" = 0
"%PCutout" = 0
"UcalcMode" = "Max"
"Priority" = "Equal"
"Enable PF limit" = false
"pfMin"	= 0.95
"Follow standard" = "1547-2018"
"Ride-through Category"	= "Category III"
"OV2 - p.u." = 1.2
"OV2 CT - sec" = 0.16
"OV1 - p.u." = 1.1
"OV1 CT - sec" = 13.0
"UV1 - p.u." = 0.88
"UV1 CT - sec" = 21.0
"UV2 - p.u." = 0.5
"UV2 CT - sec" = 2.0
"Reconnect deadtime - sec" = 3000.0
"Reconnect Pmax time - sec" = 300.0
"Permissive operation" = "Current limited"
"May trip operation" = "Trip"
"Multiple disturbances" = "Trip"

[cpf]
Category = "Legacy"
Control1 = "None"
Control2 = "None"
Control3 = "None"
pf = "None"
pfMin = 0.8
pfMax = 1
Pmin = 0
Pmax = 1
uMin = 0.92
uDbMin = 0.967
uDbMax = 1.033
uMax = 1.06  # must be less than or equal to uMinC
QlimPU = 0.44
PFlim = 1
"Enable PF limit" = false
uMinC = 1.06
uMaxC = 1.1
PminVW = 10
VWtype = "Available Power"
"%UCutoff" = 1.1
"%PCutin" = 10
"%PCutout" = 10
Efficiency = 100
Priority = "Var"
DampCoef = 0.8

[volt-var]
Control1 = "VVar"
Control2 = "None"
Control3 = "None"
pf = 1
pfMin = 0.8
pfMax = 1
Pmin = 0
Pmax = 1
uMin = 0.9399999999999999
uDbMin = 0.97
uDbMax = 1.03
uMax = 1.06
QlimPU = 0.44
PFlim = 0.9
"Enable PF limit" = false
uMinC = 1.06
uMaxC = 1.1
PminVW = 10
VWtype = "Rated Power"
"%PCutin" = 10
"%PCutout" = 10
Efficiency = 100
Priority = "Var"
DampCoef = 0.8
