["Load.test3p"]

control_type = 'CC' # 'SC' - Speed Control, 'TC' - Torque Control, 'CC' - Current Control
action_type = 'AbcCont' # Cont 
"Use default motor parameters" = false
p=2  # [p] = 1, nb of pole pairs
r_s=2.9338  # Ohm, Stator resistance
r_r=1.355  # Ohm, Rotor resistance
l_m=143.75e-3  # H, Main inductance
l_sigs=5.87e-3  # H, Stator-side stray inductance
l_sigr=5.87e-3  # H, Rotor-side stray inductance
j_rotor =0.0011 # kg/m^2 Moment of inertia of the rotor

i=0.0 
torque=10 
omega=5
