[project]
project_path = "WindowsPath('examples')"
active_project = "custom_contols"
active_project_path = "WindowsPath('examples/custom_contols')"
active_scenario = "base_case"
start_time = 2020-07-13T00:00:00
simulation_duration_min = 10.0
step_resolution_sec = 60.0
loadshape_start_time = 2020-07-13T00:00:00
simulation_type = "<SimulationType.QSTS: 'qsts'>"
control_mode = "<ControlMode.STATIC: 'Static'>"
max_control_iterations = 50
convergence_error_percent_threshold = 0.0
error_tolerance = 0.001
max_error_tolerance = 0.0
skip_export_on_convergence_error = true
dss_file = "Master_Spohn_existing_VV.dss"
dss_file_absolute_path = false
disable_pydss_controllers = false
use_controller_registry = false
[[project.scenarios]]
name = "base_case"
post_process_infos = []

[project.scenarios.snapshot_time_point_selection_config]
mode = "<SnapshotTimePointSelectionMode.NONE: 'none'>"
start_time = 2020-01-01T00:00:00
search_duration_min = 1440.0

[exports]
export_results = true
export_elements = false
export_element_types = []
export_data_tables = false
export_pv_profiles = false
export_data_in_memory = false
export_node_names_by_type = false
export_event_log = true
export_format = "<FileFormat.CSV: 'csv'>"
export_compression = false
hdf_max_chunk_bytes = 32768

[frequency]
enable_frequency_sweep = false
fundamental_frequency = 60.0
start_frequency = 1.0
end_frequency = 15.0
frequency_increment = 2.0
neglect_shunt_admittance = false
percentage_load_in_series = 50.0

[helics]
co_simulation_mode = false
iterative_mode = false
error_tolerance = 0.0001
max_co_iterations = 15
broker = "mainbroker"
broker_port = 0
federate_name = "PyDSS"
time_delta = 0.01
core_type = "zmq"
uninterruptible = true
logging_level = 5

[logging]
logging_level = "<LoggingLevel.INFO: 'info'>"
enable_console = true
enable_file = true
clear_old_log_file = false
log_time_step_updates = true

[monte_carlo]
num_scenarios = -1

[profiles]
use_profile_manager = true
source_type = "<FileFormat.HDF5: 'h5'>"
source = "profiles.hdf5"
profile_mapping = ""
is_relative_path = true

[reports]
format = "<FileFormat.HDF5: 'h5'>"
granularity = "<ReportGranularity.PER_ELEMENT_PER_TIME_POINT: 'per_element_per_time_point'>"
[[reports.types]]
enabled = false
scenarios = []
store_all_time_points = false
name = "Capacitor State Change Counts"

[[reports.types]]
enabled = false
scenarios = []
store_all_time_points = false
name = "PV Clipping"
diff_tolerance_percent_pmpp = 1.0
denominator_tolerance_percent_pmpp = 1.0

[[reports.types]]
enabled = false
scenarios = []
store_all_time_points = false
name = "PV Curtailment"
diff_tolerance_percent_pmpp = 1.0
denominator_tolerance_percent_pmpp = 1.0

[[reports.types]]
enabled = false
scenarios = []
store_all_time_points = false
name = "RegControl Tap Number Change Counts"

[project.simulation_range]
start = "00:00:00"
end = "23:59:59"

[profiles.settings]
bufferSize = 10
neglectYear = false

[profiles.settings.objects]
"Vsource.source" = "<PyDSS.dssElement.dssElement object at 0x0000028A32776390>"
"Line.sw0" = "<PyDSS.dssElement.dssElement object at 0x0000028A32776330>"
"Line.sw1" = "<PyDSS.dssElement.dssElement object at 0x0000028A305ABB30>"
"Line.sw2" = "<PyDSS.dssElement.dssElement object at 0x0000028A32301190>"
"Line.sw3" = "<PyDSS.dssElement.dssElement object at 0x0000028A32777650>"
"Transformer.tsf" = "<PyDSS.dssTransformer.dssTransformer object at 0x0000028A32777F20>"
"Line.sl_1" = "<PyDSS.dssElement.dssElement object at 0x0000028A3279BC80>"
"Line.sl_2" = "<PyDSS.dssElement.dssElement object at 0x0000028A32799B50>"
"Line.sl_3" = "<PyDSS.dssElement.dssElement object at 0x0000028A3279B110>"
"Line.sl_4" = "<PyDSS.dssElement.dssElement object at 0x0000028A3279BD40>"
"Line.sl_5" = "<PyDSS.dssElement.dssElement object at 0x0000028A3279D100>"
"Line.sl_6" = "<PyDSS.dssElement.dssElement object at 0x0000028A3279DF10>"
"Line.sl_7" = "<PyDSS.dssElement.dssElement object at 0x0000028A3279ED20>"
"Line.sl_8" = "<PyDSS.dssElement.dssElement object at 0x0000028A3279FB30>"
"Line.sl_9" = "<PyDSS.dssElement.dssElement object at 0x0000028A327A4980>"
"Line.sl_10" = "<PyDSS.dssElement.dssElement object at 0x0000028A32743BF0>"
"Line.sl_11" = "<PyDSS.dssElement.dssElement object at 0x0000028A327A6570>"
"Line.sl_12" = "<PyDSS.dssElement.dssElement object at 0x0000028A327A7380>"
"Line.sl_13" = "<PyDSS.dssElement.dssElement object at 0x0000028A327A7BF0>"
"Line.sl_14" = "<PyDSS.dssElement.dssElement object at 0x0000028A327A8FE0>"
"Line.sl_15" = "<PyDSS.dssElement.dssElement object at 0x0000028A327A9DF0>"
"Line.sl_16" = "<PyDSS.dssElement.dssElement object at 0x0000028A327AAC00>"
"Line.sl_17" = "<PyDSS.dssElement.dssElement object at 0x0000028A327ABA10>"
"Line.sl_18" = "<PyDSS.dssElement.dssElement object at 0x0000028A327B0860>"
"Line.sl_19" = "<PyDSS.dssElement.dssElement object at 0x0000028A327B1670>"
"Line.sl_20" = "<PyDSS.dssElement.dssElement object at 0x0000028A327B2480>"
"Line.sl_21" = "<PyDSS.dssElement.dssElement object at 0x0000028A327B3290>"
"Line.sl_22" = "<PyDSS.dssElement.dssElement object at 0x0000028A327B3B00>"
"Line.sl_23" = "<PyDSS.dssElement.dssElement object at 0x0000028A327B8EF0>"
"Line.sl_24" = "<PyDSS.dssElement.dssElement object at 0x0000028A327B9D00>"
"Line.sl_25" = "<PyDSS.dssElement.dssElement object at 0x0000028A327BAB10>"
"Line.sl_26" = "<PyDSS.dssElement.dssElement object at 0x0000028A327BB920>"
"Load.mpx000635970" = "<PyDSS.dssElement.dssElement object at 0x0000028A327C0770>"
"Load.mpx000460267" = "<PyDSS.dssElement.dssElement object at 0x0000028A327C3230>"
"Load.mpx000637601" = "<PyDSS.dssElement.dssElement object at 0x0000028A327C1DF0>"
"Load.mpx000594341" = "<PyDSS.dssElement.dssElement object at 0x0000028A327C2390>"
"Line.pvl_110" = "<PyDSS.dssElement.dssElement object at 0x0000028A327C3AD0>"
"Line.pvl_111" = "<PyDSS.dssElement.dssElement object at 0x0000028A327C8A10>"
"Line.pvl_113" = "<PyDSS.dssElement.dssElement object at 0x0000028A327C9FA0>"
"Line.pvl_112" = "<PyDSS.dssElement.dssElement object at 0x0000028A327CAE10>"
"PVSystem.pvgnem_mpx000635970" = "<PyDSS.dssElement.dssElement object at 0x0000028A327CBBF0>"
"PVSystem.pvgnem_mpx000460267" = "<PyDSS.dssElement.dssElement object at 0x0000028A327CCA10>"
"PVSystem.pvgnem_mpx000594341" = "<PyDSS.dssElement.dssElement object at 0x0000028A327CE540>"
"PVSystem.pvgui_mpx000637601" = "<PyDSS.dssElement.dssElement object at 0x0000028A327CF6E0>"
"PVSystem.pvgui_mpx000460267" = "<PyDSS.dssElement.dssElement object at 0x0000028A327D8770>"
"EnergyMeter.feedermeter" = "<PyDSS.dssElement.dssElement object at 0x0000028A327D97C0>"
"Fault.default" = "<PyDSS.dssElement.dssElement object at 0x0000028A327DBA70>"
"Circuit.heco19021" = "<PyDSS.dssCircuit.dssCircuit object at 0x0000028A31AD36B0>"
