["Generator.pvgui_mpx000460267"]
DER_ID = "1"
STEADY_STATE  = false
RATED_POWER_AC_VA = 10800.0
RATED_POWER_DC_WATTS = 10800.0
MPPT_ENABLE = false
RAMP_ENABLE = false
VOLT_VAR_ENABLE = false
LVRT_ENABLE = false
HVRT_ENABLE = false
LFRT_ENABLE = false
DO_EXTRA_CALCULATIONS = false
use_frequency_estimate = false
jacFlag = false
UPDATE_MODULE_PARAMETRS = false
Np = 2
Ns = 1000
Vdcmpp0 = 750.0
Vdcmpp_max = 650.0
Vdcmpp_min =  650.0
UPDATE_INVERTER_PARAMETRS = false
Vdcrated = 1000.0
Ioverload = 1.1
Vrmsrated = 177.0
Iramp_max_gradient_imag = 1.0
Iramp_max_gradient_real = 1.0
UPDATE_CIRCUIT_PARAMETRS = false
Rf_actual = 0.002
Lf_actual = 0.000025
C_actual = 3e-05
Z1_actual_real = 0.0019
Z1_actual_imag = 0.0561
R1_actual = 0.0019
X1_actual = 0.0561
UPDATE_CONTROLLER_PARAMETRS = true
Kp_GCC = 12000.0
Ki_GCC = 2000.0
Kp_DC = -2.0
Ki_DC = -10.0
Kp_Q = 0.2
Ki_Q = 10.0
wp = 200000.0
UPDATE_STEADYSTATE_PARAMETRS = false
iaI0 = 0.001
iaR0 = 1.0
maI0 = 0.0
maR0 = 0.89

