["Generator.pvgui_mpx000460267"]
DER_ID = "1"
STEADY_STATE  = false
RATED_POWER_AC_VA = 5000.0
RATED_POWER_DC_WATTS = 5000.0
MPPT_ENABLE = false
RAMP_ENABLE = false
VOLT_VAR_ENABLE = false
LVRT_ENABLE = false
HVRT_ENABLE = false
LFRT_ENABLE = false
DO_EXTRA_CALCULATIONS = false
use_frequency_estimate = false
jacFlag = false
UPDATE_PARAMETRS = false
C_actual = 3e-05
Ioverload = 1.1
Iramp_max_gradient_imag = 1.0
Iramp_max_gradient_real = 1.0
Ki_DC = -10.0
Ki_GCC = 2000.0
Ki_Q = 10.0
Kp_DC = -2.0
Kp_GCC = 6000.0
Kp_Q = 0.2
Lf_actual = 0.000025
Np = 1100
Ns = 735
R1_actual = 0.0019
Rf_actual = 0.002
Srated = 50000.0
Vdcmpp0 = 550.0
Vdcmpp_max = 650.0
Vdcmpp_min = 525.0
Vdcrated = 550.0
Vrmsrated = 177.0
X1_actual = 0.0561
Z1_actual_real = 0.0019
Z1_actual_imag = 0.0561
iaI0 = 0.001
iaR0 = 1.0
maI0 = 0.0
maR0 = 0.89
wp = 200000.0
DEBUG_SIMULATION = false
DEBUG_VOLTAGES = false
DEBUG_CURRENTS = false
DEBUG_POWER = false
DEBUG_CONTROLLERS = true
DEBUG_PLL = false
DEBUG_SOLVER = true