unit_info = {
        'CurrentsMagAng' : {'E' : 'Amp', 'O' : 'Deg'},
        'Currents': {'E': 'Amp:Re', 'O': 'Amp:Im'},
        'RatedCurrent': 'Amp',
        'EmergAmps': 'Amp',
        'NormalAmps': 'Amp',
        'normamps': 'Amp',
        'Losses': {'E' : 'kW', 'O' : 'kvar'},
        'PhaseLosses': {'E' : 'kW', 'O' : 'kvar'},
        'Powers':  {'E' : 'kW', 'O' : 'kvar'},
        'TotalPower':  {'E' : 'kW', 'O' : 'kvar'},
        'LineLosses':  {'E' : 'kW', 'O' : 'kvar'},
        'SubstationLosses':  {'E' : 'kW', 'O' : 'kvar'},
        'kV': 'kV',
        'kVARated': 'kVA',
        'kvar': 'kvar',
        'kW': 'kW',
        'kVABase': 'kVA',
        'kWh': 'kWh',
        'puVmagAngle' : {'E' : 'V:pu', 'O' : 'Deg'},
        'VoltagesMagAng': {'E' : 'V', 'O' : 'Deg'},
        'VMagAngle': {'E' : 'V', 'O' : 'Deg'},
        'Voltages': {'E': 'V:Re', 'O': 'V:Im'},
        'Vmaxpu': 'pu',
        'Vminpu': 'pu',
        'Frequency' : 'Hz',
        'Taps' : 'tap:PU',
        '%stored' : '%SOC',
        'Distance' : 'Mi'
    }

type_info = {
        'CurrentsMagAng': 'vector',
        'Currents': 'vector',
        'RatedCurrent': 'double',
        'EmergAmps': 'double',
        'NormalAmps': 'double',
        'normamps': 'Amp',
        'Losses': 'vector',
        'PhaseLosses': 'vector',
        'Powers':  'vector',
        'TotalPower':  'vector',
        'LineLosses':  'vector',
        'SubstationLosses':  'vector',
        'kV': 'double',
        'kVARated': 'double',
        'kvar': 'double',
        'kW': 'double',
        'kVABase': 'double',
        'kWh': 'double',
        'puVmagAngle': 'vector',
        'VoltagesMagAng': 'vector',
        'VMagAngle': 'vector',
        'Voltages': 'vector',
        'Vmaxpu': 'double',
        'Vminpu': 'double',
        'Frequency': 'double',
        'Taps': 'vector',
        '%stored': 'double',
        'Distance': 'double'
    }
