["Storage.1234"]
VoltageMeaElem = "storagebus"
PowerMeaElem = "Line.sw0"
Control1 = "PS"
Control2 = "None"
Control3 = "None"
BaseLoadLim = 0
ExpWindowStart = 18:00:00
ExpWindowEnd = 08:00:00
Schedule = "[0, 0, -1, 0, 1, 0, 0]"
Days = 1
PS_lb = 0
PS_ub = 0
CF_dP_lb = -50
CF_dP_ub = 50
HrCharge = 2
HrDischarge = 15
"%rateCharge" = 100
"%rateDischarge" = 100
"%kWOut" = 50
pf = 0.85
pfMin = 0.8
pfMax = 1
Pmin = 0.25
Pmax = 1
uMin = 0.95
uDbMin = 1
uDbMax = 1
uMax = 1.05
QlimPU = 0.8
PFlim = 0.85
"Enable PF limit" = true
DampCoef = 0.8
alpha = 0.7
beta = 0
