["Generator.pv_1"]
Category = "test"
Control1 = "None"
Control2 = "None"
Control3 = "None"
kV = nan
kVA = 4
maxKW = 4
KvarLimit = 1.76
"%PCutin" = 10
"%PCutout" = 10
UcalcMode = "Max"
Priority = "Equal"
"Enable PF limit" = false
pfMin = 0.95
"Follow standard" = "1547-2018"
"Ride-through Category" = "Category I"
"Category I Low Frequency Droop" = false
"OF2 - Hz" = 62.0
"OF2 CT - sec" = 0.16
"OF1 - Hz" = 61.2
"OF1 CT - sec" = 300
"UF1 - Hz" = 58.5
"UF1 CT - sec" = 300
"UF2 - Hz" = 56.5
"UF2 CT - sec" = 0.16
"db_UF" = 0.036
"db_OF" = 0.036
"k_UF" = 0.05
"k_OF" = 0.05
"minKW" = 0
"Reconnect deadtime - sec" = 3000 
"Reconnect Pmax time - sec" = 300
#"Permissive operation" = "Current limited" # not needed
"May trip operation" = "Ride-Through" #"Trip" #"Ride-Through" #
#"Multiple disturbances" = "Trip" #not needed?
alpha = 0.9
beta = 0.3
uMin = 0.95
uDbMin = 0.97
uDbMax = 1.03
uMax = 1.05
uMinC = 1.06
uMaxC = 1.1
PminVW = 0.5
CurtMode = "Rated Power"
