[Project]
"Start time" = "2019-2-23 00:00:00.0"
"Simulation duration (min)" = 54720.0
"Loadshape start time" = "2019-2-23 00:00:00.0"
"Step resolution (sec)" = 900.0
"Max Control Iterations" = 50
"Error tolerance" = 0.001
"Control mode" = "Static"
"Disable PyDSS controllers" = false
"Simulation Type" = "QSTS"
"Project Path" = "./examples"
"Active Project" = "utilidata_example"
"Active Scenario" = "base_case"
"DSS File" = "IEEE13Nodeckt.dss"
"DSS File Absolute Path" = false
"Return Results" = false

#[[Project.Scenarios]]
#name = "base_case"
#post_process_infos = []

[[Project.Scenarios]]
name = "vvo_interface"
[[Project.Scenarios.post_process_infos]]
script = "Utilidata_Interface"
config_file = "examples/utilidata_example/utilidata_config.toml"

[Exports]
"Export Mode" = "byClass"
"Export Style" = "Single file"
"Export Format" = "h5"
"Export Compression" = true
"Export Iteration Order" = "ValuesByPropertyAcrossElements"
"Export Elements" = true
"Export Data Tables" = true
"Export Data In Memory" = true
"HDF Max Chunk Bytes" = 32768
"Export Event Log" = true
"Log Results" = true

[Frequency]
"Enable frequency sweep" = false
"Fundamental frequency" = 60
"Start frequency" = 1.0
"End frequency" = 15.0
"frequency increment" = 2.0
"Neglect shunt admittance" = false
"Percentage load in series" = 50.0

[Helics]
"Co-simulation Mode" = false
"Federate name" = "PyDSS"
"Time delta" = 0.01
"Core type" = "zmq"
Uninterruptible = true
"Helics logging level" = 5

[Logging]
"Logging Level" = "INFO"
"Log to external file" = true
"Display on screen" = true
"Clear old log file" = false
"Pre-configured logging" = false

[MonteCarlo]
"Number of Monte Carlo scenarios" = -1

[Plots]
"Create dynamic plots" = false
"Open plots in browser" = false

[Reports]
Format = "h5"
[[Reports.Types]]
name = "Capacitor State Change Counts"
enabled = false

[[Reports.Types]]
name = "PV Clipping"
enabled = false

[[Reports.Types]]
name = "PV Curtailment"
enabled = false

[[Reports.Types]]
name = "RegControl Tap Number Change Counts"
enabled = false

[Profiles]
"Use profile manager" = false
source_type = "HDF5"
source = "profiles.hdf5"
"Profile mapping" = ""
is_relative_path = true
[Profiles.settings]
bufferSize =  10
neglectYear = false